### ISSUE TITLE
Steps to run the code

### ISSUE THREAD

**Issue by paragon1234** [junjun-jiang/SSPSR#5]
Thank you for sharing the wonderful code. can you please elaborate on the steps to execute the code. I have downloaded the dataset. Where to place it? Any scripts to run on dataset before training? command prompt to train?

**Comment by paragon1234** [comment]
I have figured out something:
python mains.py
```

Traceback (most recent call last):
  File "mains.py", line 306, in <module>
    main()
  File "mains.py", line 67, in main
    print(args.gpus)
AttributeError: 'Namespace' object has no attribute 'gpus'
```

**Comment by swuxyj** [comment]
python main.py train

**Comment by 12Alyssa** [comment]
Hello, I have arrived at the exact same problem. Have you found the solution to this problem？

**Comment by z4545xy** [comment]
> 我想通了一些东西：python mains.py
> 
> ```
> 
> Traceback (most recent call last):
>   File "mains.py", line 306, in <module>
>     main()
>   File "mains.py", line 67, in main
>     print(args.gpus)
> AttributeError: 'Namespace' object has no attribute 'gpus'
> ```怎么解决该问题呀？可以分享一下吗？谢谢
